Provide a default description so that if a description is not provided the script will still work. Otherwise you get a AttributeError: 'NoneType' object has no attribute 'split'